In [1]:
import pandas as pd

In [2]:
url = 'https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2022-01.parquet'

In [6]:
df = pd.read_parquet(url)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62495 entries, 0 to 62494
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   VendorID               62495 non-null  int64
 1   lpep_pickup_datetime   62495 non-null  datetime64[us]
 2   lpep_dropoff_datetime  62495 non-null  datetime64[us]
 3   store_and_fwd_flag     56200 non-null  object
 4   RatecodeID             56200 non-null  float64
 5   PULocationID           62495 non-null  int64
 6   DOLocationID           62495 non-null  int64
 7   passenger_count        56200 non-null  float64
 8   trip_distance          62495 non-null  float64
 9   fare_amount            62495 non-null  float64
 10  extra                  62495 non-null  float64
 11  mta_tax                62495 non-null  float64
 12  tip_amount             62495 non-null  float64
 13  tolls_amount           62495 non-null  float64
 14  ehail_fee              0 non-null      object
 15  improvement_surcharge  62495 non-null  float64
 16  total_amount           62495 non-null  float64
 17  payment_type           56200 non-null  float64
 18  trip_type              56200 non-null  float64
 19  congestion_surcharge   56200 non-null  float64
dtypes: datetime64[us](2), float64(13), int64(3), object(2)
memory usage: 9.5+ MB

In [10]:
url_base = 'https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2022-'

url_initial = url_base + '01.parquet'

next_months = ['02.parquet', '03.parquet', '04.parquet', '05.parquet',
        '06.parquet', '07.parquet', '08.parquet', '09.parquet', 
        '10.parquet', '11.parquet', '12.parquet']

print(f'Reading from: {url_initial}')
df = pd.read_parquet(url_initial)
print('-'*50)
print(f'Number of rows: {df.shape[0]}')

for month in next_months:
    url_current = url_base + month
    print(f'Reading from: {url_current}')
    df_current = pd.read_parquet(url_current)
    df = pd.concat([df, df_current], ignore_index=True)
    print('-'*50)
    print(f'Number of rows: {df.shape[0]}')
    
print(df)

Reading from: https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2022-01.parquet
--------------------------------------------------
Number of rows: 62495
Reading from: https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2022-02.parquet
--------------------------------------------------
Number of rows: 131894
Reading from: https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2022-03.parquet
--------------------------------------------------
Number of rows: 210431
Reading from: https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2022-04.parquet
--------------------------------------------------
Number of rows: 286567
Reading from: https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2022-05.parquet
--------------------------------------------------
Number of rows: 363458
Reading from: https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2022-06.parquet
--------------------------------------------------
Number of rows: 437176
Reading from: https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2022-07.parquet
--------------------------------------------------
Number of rows: 501368
Reading from: https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2022-08.parquet
--------------------------------------------------
Number of rows: 567297
Reading from: https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2022-09.parquet
--------------------------------------------------
Number of rows: 636328
Reading from: https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2022-10.parquet
--------------------------------------------------
Number of rows: 705650
Reading from: https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2022-11.parquet
--------------------------------------------------
Number of rows: 767963
Reading from: https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2022-12.parquet
--------------------------------------------------
Number of rows: 840402
        VendorID lpep_pickup_datetime lpep_dropoff_datetime  \
0              2  2022-01-01 00:14:21   2022-01-01 00:15:33
1              1  2022-01-01 00:20:55   2022-01-01 00:29:38
2              1  2022-01-01 00:57:02   2022-01-01 01:13:14
3              2  2022-01-01 00:07:42   2022-01-01 00:15:57
4              2  2022-01-01 00:07:50   2022-01-01 00:28:52
...          ...                  ...                   ...
840397         2  2022-12-31 23:33:00   2022-12-31 23:49:00
840398         2  2022-12-31 23:29:00   2023-01-01 00:01:00
840399         2  2022-12-31 23:05:00   2022-12-31 23:12:00
840400         2  2022-12-31 23:03:00   2022-12-31 23:18:00
840401         2  2022-12-31 23:16:00   2022-12-31 23:25:00

       store_and_fwd_flag  RatecodeID  PULocationID  DOLocationID  \
0                       N         1.0            42            42
1                       N         1.0           116            41
2                       N         1.0            41           140
3                       N         1.0           181           181
4                       N         1.0            33           170
...                   ...         ...           ...           ...
840397               None         NaN            33            79
840398               None         NaN            49           197
840399               None         NaN            54           181
840400               None         NaN             7           129
840401               None         NaN            17            61

        passenger_count  trip_distance  fare_amount  extra  mta_tax  \
0                   1.0           0.44         3.50   0.50      0.5
1                   1.0           2.10         9.50   0.50      0.5
2                   1.0           3.70        14.50   3.25      0.5
3                   1.0           1.69         8.00   0.50      0.5
4                   1.0           6.26        22.00   0.50      0.5
...                 ...            ...          ...    ...      ...
840397              NaN           3.53        20.72   0.00      0.0
840398              NaN           8.94        39.01   0.00      0.0
840399              NaN           1.27        12.11   0.00      0.0
840400              NaN           2.23        15.51   0.00      0.0
840401              NaN           1.74        12.32   0.00      0.0

        tip_amount  tolls_amount ehail_fee  improvement_surcharge  \
0             0.00           0.0      None                    0.3
1             0.00           0.0      None                    0.3
2             4.60           0.0      None                    0.3
3             0.00           0.0      None                    0.3
4             5.21           0.0      None                    0.3
...            ...           ...       ...                    ...
840397        4.89           0.0      None                    1.0
840398        8.00           0.0      None                    1.0
840399        2.62           0.0      None                    1.0
840400        3.30           0.0      None                    1.0
840401        2.66           0.0      None                    1.0

        total_amount  payment_type  trip_type  congestion_surcharge
0               4.80           2.0        1.0                  0.00
1              10.80           2.0        1.0                  0.00
2              23.15           1.0        1.0                  2.75
3               9.30           2.0        1.0                  0.00
4              31.26           1.0        1.0                  2.75
...              ...           ...        ...                   ...
840397         29.36           NaN        NaN                   NaN
840398         48.01           NaN        NaN                   NaN
840399         15.73           NaN        NaN                   NaN
840400         19.81           NaN        NaN                   NaN
840401         15.98           NaN        NaN                   NaN

[840402 rows x 20 columns]